version: '3'
services:
  v8cdn:
    image: helloz/v8cdn
    volumes:
      - ./config/config.js:/data/apps/v8cdn/dist/config.js
      - ./config/config.yaml:/data/apps/v8cdn/config.yaml
    ports:
      - 8080:8080
    restart: always
    container_name: v8cdn
    # user: "1000:1000"  # 替换为相应的 UID 和 GID